### ISSUE TITLE
r-rmarkdown failing to build on macOS for R 3.4.1

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-rmarkdown-feedstock#3]
r-rmarkdown is consistently failing to build with R 3.4.1 on macOS (I restarted the build but it failed with the same error). The problem package appears to be [r-htmltools](https://github.com/conda-forge/r-htmltools-feedstock), which is also currently failing only with R 3.4.1 on macOS ([travis](https://travis-ci.org/conda-forge/r-htmltools-feedstock/jobs/265839466#L278)). r-htmltools is failing to build because of its Rcpp dependency, so the issue is presumably related to the changes to the compiler on macOS introduced in R 3.4.

```
* installing *source* package ‘rmarkdown’ ...
** package ‘rmarkdown’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
unable to load shared object
'/Users/travis/miniconda3/conda-bld/r-rmarkdown_1503329119425/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/R/library/htmltools/libs/htmltools.so':
dlopen(/Users/travis/miniconda3/conda-bld/r-rmarkdown_1503329119425/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/R/library/htmltools/libs/htmltools.so,
6): Library not loaded: @rpath/libintl.9.dylib
  Referenced from:
  /Users/travis/miniconda3/conda-bld/r-rmarkdown_1503329119425/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/R/library/htmltools/libs/htmltools.
ERROR: lazy loading failed for package ‘rmarkdown’
```

A similar error is described in https://github.com/conda-forge/staged-recipes/issues/3452

**Comment by bgruening** [comment]
On it!

**Comment by bgruening** [comment]
It should be fixed. Sorry for the trouble.

**Comment by jdblischak** [comment]
> It should be fixed. Sorry for the trouble.

Thanks for the quick fix, @bgruening!

If it's not too hard to explain, how did you fix the problem? Both r-rmarkdown and r-htmltools are now built with R 3.4.1 without any new commits to either repo. I'm hoping to one day I'd like to close more issues than I open :-)
