### ISSUE TITLE
Pin pandoc for 1.5

### ISSUE THREAD

**Issue by rasmusagren** [conda-forge/r-rmarkdown-feedstock#7]
Pandoc should be pinned to version <2 for r-markdown 1.5. It's already fixed for 1.6 and not an issue for >=1.8.

**Comment by jdblischak** [comment]
@rasmusagren Do you have a specific need to install r-rmarkdown 1.5? What is your use case?

In general we don't go back through all the previous versions when a dependency changes. And if you have a specific legacy environment you need to maintain, you can specify the pandoc dependency in an environment.yaml file, e.g.:

```
name: legacy-project
channels:
- conda-forge
- defaults
dependencies:
- pandoc=1.19.2
- r-rmarkdown=1.5
```

**Comment by rasmusagren** [comment]
I see. No, I have no specific need for version 1.5. Thanks!

**Comment by jdblischak** [comment]
> I see. No, I have no specific need for version 1.5. Thanks!

No problem. Thanks for your close attention to detail! :-)

**Comment by rasmusagren** [comment]
Haha, it wasn't that I was browsing for recipes to update. It was that I had a Conda environment for a project with pinned versions, and it broke after a newer version of pandoc was installed. Rather than pinning pandoc, which might be confusing for a future user, I thought it would be better to go to the source of the problem and fix the recipe. But I get the point about not constantly having to go through and maintain old recipes.
